#!/usr/bin/env bash
set -euo pipefail

# Enable trace with TRACE=1
if [[ ${TRACE:-0} -eq 1 ]]; then set -x; fi

IMAGE_DEFAULT="deepdrill:latest"   # your locally built image tag
NAME_DEFAULT="deepdrill-${USER:-user}-$$"
JOBS="$(nproc)"; INI=""; OUT="out"; IMAGE="${DEEPDRILL_IMAGE:-$IMAGE_DEFAULT}"; NAME="$NAME_DEFAULT"; TARGET=""; DETACH=0; FOLLOW=0; PULL=0

usage(){ cat <<EOF
Usage: $(basename "$0") <project_dir> [options]

Options:
  -c, --config FILE   .ini filename inside project_dir (default: auto-detect if only one)
  -o, --out DIR       output directory (default: out)
  -j, --jobs N        make -j N (default: $(nproc))
  -t, --target NAME   optional make target after render (e.g. deepzoom.mov)
  -i, --image IMG     container image (default: $IMAGE_DEFAULT)
  -n, --name NAME     container name (default: autogenerated)
      --detach        run container detached
      --follow        after start, stream logs (implies --detach)
      --pull          docker pull the image before run (otherwise require local)
  -h, --help          show this help

Examples:
  $(basename "$0") ./project -c quick-1080p.ini --target deepzoom.mov
  $(basename "$0") ./project -i deepdrill

Manual docker (equivalent):
  docker run --rm -t -v /abs/project:/work \
    deepdrill deepdrill-cmd -c quick-1080p.ini -o out -j $(nproc) --target deepzoom.mov
EOF
}

[[ $# -ge 1 ]] || { usage; exit 1; }
PROJ="$1"; shift || true

while [[ $# -gt 0 ]]; do
  case "$1" in
    -c|--config) INI="$2"; shift 2;;
    -o|--out)    OUT="$2"; shift 2;;
    -j|--jobs)   JOBS="$2"; shift 2;;
    -t|--target) TARGET="$2"; shift 2;;
    -i|--image)  IMAGE="$2"; shift 2;;
    -n|--name)   NAME="$2"; shift 2;;
    --detach)    DETACH=1; shift;;
    --follow)    DETACH=1; FOLLOW=1; shift;;
    --pull)      PULL=1; shift;;
    -h|--help)   usage; exit 0;;
    *) echo "Unknown arg: $1"; usage; exit 1;;
  esac
done

# Ensure docker exists
command -v docker >/dev/null 2>&1 || { echo "docker not found in PATH"; exit 127; }

# Resolve absolute project path portably (no need for realpath)
PROJ_ABS="$(cd "$PROJ" && pwd -P)" || { echo "Project dir not found: $PROJ"; exit 1; }

# Auto-detect .ini if not provided
if [[ -z "$INI" ]]; then
  mapfile -t INIS < <(find "$PROJ_ABS" -maxdepth 1 -type f -name '*.ini' | sort)
  if [[ ${#INIS[@]} -eq 1 ]]; then
    INI="$(basename "${INIS[0]}")"
  else
    echo "Please specify --config. Found:"; printf '  %s
' "${INIS[@]:-<none>}"; exit 1
  fi
fi

# Ensure image exists locally (unless --pull)
if ! docker image inspect "$IMAGE" >/dev/null 2>&1; then
  if [[ "$PULL" -eq 1 ]]; then
    echo "Image '$IMAGE' not found locally. Pulling..."; docker pull "$IMAGE"
  else
    echo "Image '$IMAGE' not found locally. Build it (e.g. 'docker build -t deepdrill .') or use --pull."; exit 1
  fi
fi

RUN_ARGS=(--rm -t --name "$NAME" -v "$PROJ_ABS:/work")
CMD=(deepdrill-cmd -c "$INI" -o "$OUT" -j "$JOBS")
[[ -n "$TARGET" ]] && CMD+=(--target "$TARGET")

# Echo command in trace mode
if [[ ${TRACE:-0} -eq 1 ]]; then
  printf 'docker run'; printf ' %q' "${RUN_ARGS[@]}"; printf ' %q' "$IMAGE" "${CMD[@]}"; printf '
'
fi

if [[ "$DETACH" -eq 1 ]]; then
  docker run -d "${RUN_ARGS[@]}" "$IMAGE" "${CMD[@]}"
  if [[ "$FOLLOW" -eq 1 ]]; then
    docker logs -f "$NAME"
  else
    echo "Started container: $NAME"
  fi
else
  docker run "${RUN_ARGS[@]}" "$IMAGE" "${CMD[@]}"
fi

